# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy_please

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        file_name: .env.production
        envkey_VITE_OPEN_WEATHER_MAP_API_KEY: ${{ secrets.OPEN_WEATHER_MAP_API_KEY }}
        envkey_my_name: ${{ secrets.MY_NAME }}
        envkey_VITE_OPEN_WEATHER_MAP_CURRENT_WEATHER_API_BASE: https://api.openweathermap.org/data/2.5/weather
        envkey_VITE_OPEN_WEATHER_MAP_WEATHER_FORECAST_API_BASE: https://api.openweathermap.org/data/2.5/forecast
    - run: cat .env
    - run: yarn
    - run: yarn build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist

